
import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    // MASTER
    NEXT_PUBLIC_SUPABASE_URL_MASTER: process.env.NEXT_PUBLIC_SUPABASE_URL_MASTER || "❌ MANQUANT",
    NEXT_PUBLIC_SUPABASE_ANON_KEY_MASTER: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY_MASTER ? "✅ PRÉSENT" : "❌ MANQUANT",
    SUPABASE_SERVICE_ROLE_KEY_MASTER: process.env.SUPABASE_SERVICE_ROLE_KEY_MASTER ? "✅ PRÉSENT" : "❌ MANQUANT",

    // NANTES PUBLIC
    NEXT_PUBLIC_SUPABASE_URL_FR_NANTES: process.env.NEXT_PUBLIC_SUPABASE_URL_FR_NANTES || "❌ MANQUANT",
    NEXT_PUBLIC_SUPABASE_ANON_KEY_FR_NANTES: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY_FR_NANTES ? "✅ PRÉSENT" : "❌ MANQUANT",
    SUPABASE_SERVICE_ROLE_KEY_FR_NANTES: process.env.SUPABASE_SERVICE_ROLE_KEY_FR_NANTES ? "✅ PRÉSENT" : "❌ MANQUANT",

    // NANTES STAFF
    NEXT_PUBLIC_SUPABASE_URL_FR_NANTES_STAFF: process.env.NEXT_PUBLIC_SUPABASE_URL_FR_NANTES_STAFF || "❌ MANQUANT",
    NEXT_PUBLIC_SUPABASE_ANON_KEY_FR_NANTES_STAFF: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY_FR_NANTES_STAFF ? "✅ PRÉSENT" : "❌ MANQUANT",
    SUPABASE_SERVICE_ROLE_KEY_FR_NANTES_STAFF: process.env.SUPABASE_SERVICE_ROLE_KEY_FR_NANTES_STAFF ? "✅ PRÉSENT" : "❌ MANQUANT",

    // ENVIRONNEMENT
    NODE_ENV: process.env.NODE_ENV,
    VERCEL_ENV: process.env.VERCEL_ENV || "non Vercel",
  });
}
